"use strict";
exports.__esModule = true;
#;
Usage: node;
client.js;
#;
build: tsc;
client.ts;
var socket_io_client_1 = require("socket.io-client");
var socket = socket_io_client_1.io('http://localhost:31173');
socket.on('tick', function (data) { return console.log("new tick at " + data); });
socket.on('message', function (data) { console.log(data); tick = data; });
